source 'https://rubygems.org'

gem 'rails', '4.2.10'
gem 'rails-api'
gem 'activesupport'
gem 'activerecord-postgis-adapter'
gem 'pg', '~> 0.18'

#gem 'activerecord-jdbcpostgresql-adapter', :platform => 'jruby'
gem 'devise'
gem 'rabl'
#gem 'ruby-debug19', :require => 'ruby-debug'
#gem 'activerecord-postgres-hstore'
group :test, :development do
  gem 'rspec-rails'
  gem 'factory_girl_rails', :require => false
  gem 'guard'
  # gem 'rails_helper'
end
gem 'twitter'
gem 'bunny'
gem 'redis'
gem 'devise-token_authenticatable'
gem 'paper_trail'
gem 'geocoder'
gem 'foursquare2'
gem 'gmaps4rails'
gem "friendly_id"
gem 'pg_search'
gem 'textacular'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'
gem 'oauth2'
gem 'sidekiq'
gem 'protected_attributes'
gem 'puma'
gem 'nokogiri'
#gem 'jruby-openssl', :platform => 'jruby'
gem 'tzinfo-data'
gem 'httparty'
gem 'instagram'
gem 'figaro'
gem 'redis-rails'
gem 'google_plus'
gem 'nested-hstore'
gem 'youtube_it'
gem 'clean_pagination'
gem 'surus'
gem 'oj'
gem "koala"
gem 'fb_graph'
#gem 'logstash-logger'
gem 'mechanize'
gem 'chronic'
require 'rbconfig'
# if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i
#   gem 'wdm', '>= 0.1.0'
# end

#gem 'capsule_crm'
#gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
#gem 'apipie-rails'
